import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Assignment 14</title>
        <meta name="description" content="Generated by Scott Tennison" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            <a
              href="https://github.com/scotttennison/CS5513-Week14-2023-ScottTennison"
              rel="noopener noreferrer"
            >
              <Image
                src="/github-logo.png"
                alt="Github Logo"
                className={styles.vercelLogo}
                width={100}
                height={100}
                priority
              />
            </a>
          </p>
          <div>
            <a
              href="cs-5513-week14-2023-scott-ten-git-f52631-scottennison7-gmailcom.vercel.app"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>

          <Link href="/members" className={styles.card} rel="noopener noreferrer">
            <h2>
              Members <span>-&gt;</span>
            </h2>
            <p>
              Description about Members section.
            </p>
          </Link>
        


        <Link
          href="/events"  
          className={styles.card}
          rel="noopener noreferrer"
        >
          <h2>
            Events <span>-&gt;</span>
          </h2>
          <p>
            Description about Events section.
          </p>
        </Link>

        <Link
          href="/courses"  
          className={styles.card}
          rel="noopener noreferrer"
        >
          <h2>
            Courses <span>-&gt;</span>
          </h2>
          <p>
            Description about Courses section.
          </p>
        </Link>

      </div>
    </main >
    </>
  )
}
